import sys.io.File;

using Lambda;
using StringTools;

class LuaWrapperBuilder {
	public static function main():Void {
		final root = Xml.parse(File.getContent('coldsteel.xml')).firstElement();
		File.saveContent('src/lua_wrapper.cc', getLuaWrapperContent(root));
	}

	private static function getLuaWrapperContent(root:Xml):String {
		final functions = getFunctions(root);
		final constants = getConstants(root);
		return getHeader() + functions.map(f -> getFunctionBody(f)).join('') + getLuaOpen(functions, constants);
	}

	private static function getHeader():String {
		return '// Generated by LuaWrapperBuilder.hx - do not edit manually.
extern "C" {
#include "lua.h"
#include "lauxlib.h"
}
#include "engine.h"
#undef DrawText
#undef LoadString

';
	}

	private static function getFunctionBody(func:Function):String {
		var args = '';
		final params = func.params.array();
		for (i in 0...params.length)
			args += (i > 0 ? ', ' : '') + getArgExpr(params[i].type, i + 1);
		if (func.type == 'void')
			return 'static int cs_${func.name}(lua_State *L) {\n  ${func.name}($args);\n  return 0;\n}\n\n';
		return 'static int cs_${func.name}(lua_State *L) {\n  ${getReturnExpr(func.name, func.type, args)};\n  return 1;\n}\n\n';
	}

	private static function getArgExpr(type:String, index:Int):String {
		return switch (type) {
			case 'bool_t': '(bool_t)lua_toboolean(L, $index)';
			case 'bool': '(bool)lua_toboolean(L, $index)';
			case 'int': '(int)lua_tonumber(L, $index)';
			case 'Channel': '(Channel)lua_tonumber(L, $index)';
			case 'float': '(float)lua_tonumber(L, $index)';
			case 'p.q(const).char' | 'q(const).char': '(const char *)lua_tostring(L, $index)';
			case 'p.void': '(void *)lua_touserdata(L, $index)';
			default: getPointerArgExpr(type, index);
		};
	}

	private static function getPointerArgExpr(type:String, index:Int):String {
		if (type.startsWith('p.q(const).'))
			return '(${type.substr(11)} *)lua_touserdata(L, $index)';
		if (type.startsWith('p.'))
			return '(${type.substr(2)} *)lua_touserdata(L, $index)';
		throw 'Unknown argument type: $type';
	}

	private static function getReturnExpr(name:String, type:String, args:String):String {
		return switch (type) {
			case 'bool_t' | 'bool': 'lua_pushboolean(L, $name($args) != 0)';
			case 'int' | 'float' | 'Channel': 'lua_pushnumber(L, (lua_Number)$name($args))';
			case 'p.q(const).char' | 'q(const).char': 'lua_pushstring(L, $name($args))';
			default: 'lua_pushlightuserdata(L, (void *)$name($args))';
		};
	}

	private static function getLuaOpen(functions:Iterable<Function>, constants:Iterable<Constant>):String {
		final funcTable = functions.map(f -> '\t{"${f.name}", cs_${f.name}},\n').join('');
		final constTable = constants.map(c -> '\t{"${c.name}", ${c.value}},\n').join('');
		return '
static const struct { const char *name; lua_CFunction fn; } cs_Functions[] = {
$funcTable};

static const struct { const char *name; int value; } cs_Constants[] = {
$constTable};

extern "C" int luaopen_coldsteel(lua_State *L) {
  int i;
  lua_newtable(L);
  for (i = 0; i < (int)(sizeof(cs_Functions) / sizeof(cs_Functions[0])); i++) {
    lua_pushcfunction(L, cs_Functions[i].fn);
    lua_setfield(L, -2, cs_Functions[i].name);
  }
  for (i = 0; i < (int)(sizeof(cs_Constants) / sizeof(cs_Constants[0])); i++) {
    lua_pushinteger(L, cs_Constants[i].value);
    lua_setfield(L, -2, cs_Constants[i].name);
  }
  lua_setglobal(L, "coldsteel");
  lua_getglobal(L, "coldsteel");
  return 1;
}
';
	}

	private static function getFunctions(element:Xml):Iterable<Function> {
		final functions = XmlParser.elements(element, 'cdecl').filter(c -> XmlParser.attribute(c, 'kind') == 'function').map(f -> Function.fromXml(f));
		final childFunctions = XmlParser.elements(element).flatMap(c -> getFunctions(c));
		return functions.concat(childFunctions).filter(f -> !f.name.startsWith('_'));
	}

	private static function getConstants(element:Xml):Iterable<Constant> {
		final constants = XmlParser.elements(element, 'constant').map(c -> Constant.fromXml(c));
		final childConstants = XmlParser.elements(element).flatMap(c -> getConstants(c));
		return constants.concat(childConstants);
	}
}

private class Function {
	public final name:String;
	public final type:String;
	public final params:Iterable<Param>;

	public function new(name:String, type:String, params:Iterable<Param>) {
		this.name = name;
		this.type = type;
		this.params = params.array();
	}

	public static function fromXml(element:Xml):Function {
		final attributelistElem = XmlParser.elements(element, 'attributelist')[0];
		final parmlistElem = XmlParser.elements(attributelistElem, 'parmlist')[0];
		final params = (parmlistElem != null) ? XmlParser.elements(parmlistElem, 'parm') : [];
		final baseType = XmlParser.attribute(element, 'type');
		final decl = XmlParser.attribute(element, 'decl');
		return new Function(XmlParser.attribute(element, 'name'), XmlParser.resolveReturnType(baseType, decl), params.map(p -> Param.fromXml(p)));
	}
}

private class Param {
	public final type:String;

	public function new(type:String) {
		this.type = type;
	}

	public static function fromXml(element:Xml):Param {
		return new Param(XmlParser.attribute(element, 'type'));
	}
}

private class Constant {
	public final name:String;
	public final value:String;

	public function new(name:String, value:String) {
		this.name = name;
		this.value = value;
	}

	public static function fromXml(element:Xml):Constant {
		return new Constant(XmlParser.attribute(element, 'name'), XmlParser.attribute(element, 'value'));
	}
}

private class XmlParser {
	public static function attribute(element:Xml, name:String):String {
		final attributes = element.elementsNamed('attributelist').next().elementsNamed('attribute');
		for (attr in attributes) {
			if (attr.get('name') == name) {
				return attr.get('value');
			}
		}
		return '';
	}

	public static function elements(root:Xml, ?name:String):Array<Xml> {
		final it = (name != null) ? root.elementsNamed(name) : root.elements();
		return [for (el in it) el];
	}

	public static function resolveReturnType(baseType:String, decl:String):String {
		final parenIdx = decl.lastIndexOf(')');
		if (parenIdx < 0) return baseType;
		final suffix = decl.substr(parenIdx + 1);
		return (suffix == 'p.') ? 'p.$baseType' : baseType;
	}
}