coldsteel run _build\examples\box
coldsteel run _build\examples\box_lightmap
coldsteel run _build\examples\collision
coldsteel run _build\examples\fog
coldsteel run _build\examples\hello
coldsteel run _build\examples\joystick
coldsteel run _build\examples\lighting
coldsteel run _build\examples\lightmap
coldsteel run _build\examples\listener
coldsteel run _build\examples\primitives
coldsteel run _build\examples\render_to_texture
coldsteel run _build\examples\screen_to_world
coldsteel run _build\examples\shadows
coldsteel run _build\examples\specular
coldsteel run _build\examples\sprites
coldsteel run _build\examples\terrain
coldsteel run _build\examples\test
coldsteel run _build\examples\texture_from_pixmap
coldsteel run _build\examples\triangle
coldsteel run _build\examples\viewport
coldsteel run _build\examples\world_to_screen
