csrun _build\examples\box
csrun _build\examples\collision
csrun _build\examples\editor
csrun _build\examples\fog
csrun _build\examples\hello
csrun _build\examples\joystick
csrun _build\examples\lighting
csrun _build\examples\lightmap
csrun _build\examples\listener
csrun _build\examples\primitives
csrun _build\examples\render_to_texture
csrun _build\examples\screen_to_world
csrun _build\examples\shadows
csrun _build\examples\specular
csrun _build\examples\sprites
csrun _build\examples\terrain
csrun _build\examples\test
csrun _build\examples\texture_from_pixmap
csrun _build\examples\triangle
csrun _build\examples\viewport
csrun _build\examples\world_to_screen
csrun _build\examples\xml
