#!/bin/sh
cd `dirname $0`
python3 csbuild.py desktop $1
sleep 0.001
cd $1.build
case "$(uname -s)" in
    Darwin)
        open "`(basename $1)`.app"
        ;;
    *)
        ./`(basename $1)`
        ;;
esac
