#!/bin/sh
cd `dirname $0`
python3 csbuild.py $1
echo "Launching server..."
echo "- Go to http://localhost:8000 on your browser."
echo "- Ctrl+C and confirm to finish."
cd $1.build
python3 -m http.server
