/**
 * @file
 * Constructive Solid Geometry (CSG). A CSG builder accumulates convex primitives (union and
 * difference) and converts the resulting solid into a single mesh, following the level-editor
 * mental model: start from solid space, carve rooms out of it with CSG_SUBTRACT, then fill them
 * with geometry using CSG_ADD. Operations are processed strictly in call order.
 */
#pragma once

#include "common.h"

#define CSG_ADD 0 /**< Union: place solid geometry with outward faces. */
#define CSG_SUBTRACT 1 /**< Difference: carve a cavity with inward faces. */

typedef struct CSGBuilder CSGBuilder; /* opaque CSG builder handle */

#ifdef __cplusplus
extern "C"
{
#endif

  /**
   * Creates a CSG builder that starts with a solid world (solid everywhere).
   *
   * @return The new CSG builder.
   */
  EXPORT CSGBuilder *CALL CreateCsg();

  /**
   * Frees a CSG builder.
   *
   * @param csg The CSG builder to free.
   */
  EXPORT void CALL FreeCsg(CSGBuilder *csg);

  /**
   * Resets the builder to an empty (solid everywhere) world, reusing the handle.
   *
   * @param csg The CSG builder to clear.
   */
  EXPORT void CALL ClearCsg(CSGBuilder *csg);

  /**
    * Adds a box primitive to the CSG solid.
    *
    * A first CSG_ADD renders nothing (the box is buried in the solid world); carve rooms first
    * and then fill them. Rotation is in degrees, matching RotateMesh.
    *
    * UVs are autogenerated per face using classic BSP axial projection: the texture is applied
    * along the world axis plane closest to the face, then shifted, rotated and scaled as given.
    * A scale of 1 means 1 texel per world unit, so a 64x64 texture tiles every 64 units.
    *
    * @param csg The CSG builder to modify.
    * @param operation The CSG operation to apply (CSG_ADD or CSG_SUBTRACT).
    * @param texture The texture for the primitive's surfaces, or NULL.
    * @param x The X position of the box center.
    * @param y The Y position of the box center.
    * @param z The Z position of the box center.
    * @param pitch The pitch rotation in degrees.
    * @param yaw The yaw rotation in degrees.
    * @param roll The roll rotation in degrees.
    * @param width The box width.
    * @param height The box height.
    * @param depth The box depth.
    * @param uoffset The texture U offset in texels.
    * @param voffset The texture V offset in texels.
    * @param tex_rotation The texture rotation in degrees.
    * @param uscale The texture U scale (1 = 1 texel per world unit).
    * @param vscale The texture V scale (1 = 1 texel per world unit).
    */
  EXPORT void CALL AddCsgBox(CSGBuilder *csg, int operation, ITexture *texture,
                             float x, float y, float z, float pitch, float yaw, float roll,
                             float width, float height, float depth,
                             float uoffset, float voffset, float tex_rotation,
                             float uscale, float vscale);

  /**
    * Adds a cylinder primitive to the CSG solid.
    *
    * @param csg The CSG builder to modify.
    * @param operation The CSG operation to apply (CSG_ADD or CSG_SUBTRACT).
    * @param texture The texture for the primitive's surfaces, or NULL.
    * @param x The X position of the cylinder center.
    * @param y The Y position of the cylinder center.
    * @param z The Z position of the cylinder center.
    * @param pitch The pitch rotation in degrees.
    * @param yaw The yaw rotation in degrees.
    * @param roll The roll rotation in degrees.
    * @param radius The cylinder radius.
    * @param height The cylinder height.
    * @param segments The number of radial segments.
    * @param uoffset The texture U offset in texels.
    * @param voffset The texture V offset in texels.
    * @param tex_rotation The texture rotation in degrees.
    * @param uscale The texture U scale (1 = 1 texel per world unit).
    * @param vscale The texture V scale (1 = 1 texel per world unit).
    */
  EXPORT void CALL AddCsgCylinder(CSGBuilder *csg, int operation, ITexture *texture,
                                  float x, float y, float z, float pitch, float yaw, float roll,
                                  float radius, float height, int segments,
                                  float uoffset, float voffset, float tex_rotation,
                                  float uscale, float vscale);

  /**
    * Adds a cone primitive to the CSG solid.
    *
    * @param csg The CSG builder to modify.
    * @param operation The CSG operation to apply (CSG_ADD or CSG_SUBTRACT).
    * @param texture The texture for the primitive's surfaces, or NULL.
    * @param x The X position of the cone center.
    * @param y The Y position of the cone center.
    * @param z The Z position of the cone center.
    * @param pitch The pitch rotation in degrees.
    * @param yaw The yaw rotation in degrees.
    * @param roll The roll rotation in degrees.
    * @param radius The cone base radius.
    * @param height The cone height.
    * @param segments The number of radial segments.
    * @param uoffset The texture U offset in texels.
    * @param voffset The texture V offset in texels.
    * @param tex_rotation The texture rotation in degrees.
    * @param uscale The texture U scale (1 = 1 texel per world unit).
    * @param vscale The texture V scale (1 = 1 texel per world unit).
    */
  EXPORT void CALL AddCsgCone(CSGBuilder *csg, int operation, ITexture *texture,
                              float x, float y, float z, float pitch, float yaw, float roll,
                              float radius, float height, int segments,
                              float uoffset, float voffset, float tex_rotation,
                              float uscale, float vscale);

  /**
    * Adds a wedge (right-triangular prism) primitive to the CSG solid.
    *
    * The wedge is centered on its bounding box: it spans +/-width/2 (X), +/-height/2 (Y) and
    * +/-depth/2 (Z). The tall edge is at the back (z = -depth/2) and the thin edge at the front
    * (z = +depth/2); moving +Z climbs the slope. Placing the wedge on a floor needs a -height/2
    * Y offset.
    *
    * @param csg The CSG builder to modify.
    * @param operation The CSG operation to apply (CSG_ADD or CSG_SUBTRACT).
    * @param texture The texture for the primitive's surfaces, or NULL.
    * @param x The X position of the wedge center.
    * @param y The Y position of the wedge center.
    * @param z The Z position of the wedge center.
    * @param pitch The pitch rotation in degrees.
    * @param yaw The yaw rotation in degrees.
    * @param roll The roll rotation in degrees.
    * @param width The wedge width.
    * @param height The wedge height.
    * @param depth The wedge depth.
    * @param uoffset The texture U offset in texels.
    * @param voffset The texture V offset in texels.
    * @param tex_rotation The texture rotation in degrees.
    * @param uscale The texture U scale (1 = 1 texel per world unit).
    * @param vscale The texture V scale (1 = 1 texel per world unit).
    */
  EXPORT void CALL AddCsgWedge(CSGBuilder *csg, int operation, ITexture *texture,
                               float x, float y, float z, float pitch, float yaw, float roll,
                               float width, float height, float depth,
                               float uoffset, float voffset, float tex_rotation,
                               float uscale, float vscale);

  /**
   * Builds the final mesh from the CSG solid.
   *
   * The result is a concave mesh with per-triangle flat normals and a fixed material, similar to
   * FixMaterials. Faces are grouped into one surface per texture: all primitives sharing the same
   * texture (including NULL) are merged into the same mesh buffer. On an untouched builder, an
   * empty mesh is returned.
   *
   * @param csg The CSG builder to convert.
   * @return A new mesh with the CSG result.
   */
  EXPORT IMesh *CALL CsgMesh(CSGBuilder *csg);

#ifdef __cplusplus
} /* extern "C" */
#endif